#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
IOS_DIR="$ROOT_DIR/ios"
UPSTREAM_REPO="${ZAPPA_FIREFOX_IOS_REPO:-https://github.com/mozilla-mobile/firefox-ios.git}"
WORKTREE_DIR="${ZAPPA_FIREFOX_IOS_WORKTREE:-$ROOT_DIR/.worktrees/firefox-ios}"
OVERLAY_DIR="$WORKTREE_DIR/zappa-overlay"

if [[ "${1:-}" == "--help" ]]; then
  cat <<EOF
Usage: ios/scripts/bootstrap-firefox-ios.sh [--refresh]

Clones Firefox iOS into:
  $WORKTREE_DIR

Then copies the Zappa iOS overlay into:
  $OVERLAY_DIR

Set ZAPPA_FIREFOX_IOS_WORKTREE to choose another location.
Set ZAPPA_FIREFOX_IOS_REPO to use a fork.
EOF
  exit 0
fi

mkdir -p "$(dirname "$WORKTREE_DIR")"

if [[ ! -d "$WORKTREE_DIR/.git" ]]; then
  git clone --depth 1 --filter=blob:none "$UPSTREAM_REPO" "$WORKTREE_DIR"
elif [[ "${1:-}" == "--refresh" ]]; then
  git -C "$WORKTREE_DIR" fetch --depth 1 origin
  git -C "$WORKTREE_DIR" reset --hard origin/main
fi

rm -rf "$OVERLAY_DIR"
mkdir -p "$OVERLAY_DIR"
rsync -a --delete "$IOS_DIR/ZappaRewriteKit/" "$OVERLAY_DIR/ZappaRewriteKit/"

cat > "$OVERLAY_DIR/README.md" <<EOF
# Zappa overlay

This directory is generated by zappa-rewrite/ios/scripts/bootstrap-firefox-ios.sh.

Add ZappaRewriteKit as a local Swift package in Xcode, then wire it into Firefox iOS browser chrome and the active tab WKWebView.
EOF

echo "Firefox iOS worktree: $WORKTREE_DIR"
echo "Zappa overlay: $OVERLAY_DIR"
